run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosimple
    - typecheck
    - revive
    - gocritic
    - gofmt
    - goimports
    - misspell

linters-settings:
  revive:
    severity: warning
    rules:
      - name: var-naming
      - name: indent-error-flow
      - name: error-strings
      - name: receiver-naming

  errcheck:
    check-type-assertions: true
    check-blank: true

  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
        - unused
